module.exports = {
	test: {
		src: ['<%= cfg.dist %>email.html'],
		options: {
			subject: '<%= cfg.deploy.dir %>',
			username: '<%= cfg.litmus.user %>',
			password: '<%= cfg.litmus.pass %>',
			url: '<%= cfg.litmus.url %>',
			clients: [
				// "chromeyahoo",
				// "ffyahoo",
				// "yahoo",
				// "thunderbirdlatest",
				// "plaintext",
				// "aolonline",
				// "colorblind",
				// "notes7",
				// "notes8",
				// "notes85",
				// "notes9",
				// "gmxde",
				// "ffgmxde",
				// "chromegmxde",
				// "webde",
				// "ffwebde",
				// "chromewebde",
				// "comcast",
				// "ffcomcast",
				// "chromecomcast",
				// "mailru",
				// "chromemailru",
				// "ffmailru",
				// "freenetde",
				// "fffreenetde",
				// "chromefreenetde",
				// "tonlinede",
				// "fftonlinede",
				// "chrometonlinede",
				// "orangefr",
				// "fforangefr",
				// "chromeorangefr",
				// "sfr",
				// "ffsfr",
				// "chromesfr",
				// "libero",
				// "fflibero",
				// "chromelibero",
				"ol2000",
				"ol2002",
				"ol2003",
				"ol2007",
				"ol2010",
				"ol2013",
				"gmailnew",
				"ffgmailnew",
				"chromegmailnew",
				"ol2015",
				"ol2011",
				"outlookcom",
				"ffoutlookcom",
				"chromeoutlookcom",
				"ipad",
				"ipadmini",
				"iphone6",
				"iphone6plus",
				"ffaolonline",
				"chromeaolonline",
				"googleapps",
				"ffgoogleapps",
				"chromegoogleapps",
				"office365",
				"ffoffice365",
				"chromeoffice365",
				"ol2013dpi120",
				"ol2016",
				"androidgmailapp",
				"android4",
				"iphone6s",
				"iphone6splus",
				"appmail9",
				"ipadpro13in",
				"ffgoogleinbox",
				"chromegoogleinbox",
				"iphonese",
				"windows10mail",
				"appmail10",
				"iphone7",
				"android5",
				"android6",
				"androidgmailimap",
				"iphone7plus",
				"gmailios",
				"androidgoogleinbox",
				"googleinboxios",
				"androidsamsung6",
				"iphone8",
				"iphone8plus",
				"iphonex",
				"androidoutlook",
				"appmail11"
			]
		}
	}
};
